name: Auto-merge Exercism Syncer PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, labeled, unlabeled]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: automerge-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

jobs:
  debug-and-automerge:
    runs-on: ubuntu-latest
    # Only act on Exercism Syncer PRs
    if: >
      github.event.pull_request != null &&
      (
        github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]' ||
        github.event.pull_request.user.login == 'exercism-solutions-syncer'
      )
    steps:
      - name: Log PR metadata
        run: |
          echo "PR #${{ github.event.pull_request.number }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Base: ${{ github.event.pull_request.base.ref }}"
          echo "Head: ${{ github.event.pull_request.head.ref }}"

      - name: Enable GitHub auto-merge
        # Pinned SHA for peter-evans/enable-pull-request-automerge@v3.0.0
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge  # or squash, rebase

      - name: Attempt immediate merge if already mergeable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch --auto || true
