# .github/workflows/automerge_exercism_syncer.yml
name: Auto-Merge Exercism Syncer PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    # Only run when the PR is from the Exercism Syncer app
    if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]' 
    steps:
      - name: Enable auto-merge on this PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge    # or squash / rebase per your preference

